---
title: "Differential Expression Analysis in _Syngnathus scovelli_"
author: "Coley Tosto"
date: "`r Sys.Date()`"
output:
  html_document:
    df_print: paged
    code_folding: show
    toc: yes
    toc_float: yes
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir='../',fig_path="../imgs/")
```

``` {r library, include = FALSE}
#This is a cohesive list of all the libraries used in this document
library(DESeq2)
```

``` {r functions}

```

``` {r read-data}
#The abundance matrix generated via salmon and tximport to be used for the DE analysis
SS_txi.salmon <- readRDS("data/txi.salmon_SS.RDS")

#The samples file generated for tximport
SS_samples <- read.table("SS_samples.txt", header = TRUE)

#Make sure the conditions are in the samples file as a factor
SS_samples$Sex <- as.factor(SS_samples$Sex)
SS_samples$Organ <- as.factor(SS_samples$Organ)

#Add a column to sample data that contains the Submission number for each project
SS_samples$sub_num <- c(rep("PRJNA295858", 10),
                        rep("SRA582537", 7),
                        rep("SRA1439291", 5),
                        rep("SRA1651277", 4),
                        rep("SRA1439291", 5),
                        rep("SRA966117", 10))
```

The package `DESeq2` was used for the differential expression analysis outlined below.

# Single factor analysis - Comparing Males v Females
To analyze your data with DESeq2 you must first generate the DESeqDataSet. In order to do this we need the abundance matrix generated with `tximport` and a `samples` file that lays out all of the conditions.
```{r DESeqDataSet, message=FALSE, warning=FALSE}
#Create the DESeq dataset
dds_SS <- DESeqDataSetFromTximport(SS_txi.salmon, 
                                   colData = SS_samples,
                                   design = ~ Sex)

```
