---
title: '_Stigmatopora macropterygia_: figures'
output: github_document
  #pdf_document: default
  #html_document:
    #df_print: paged
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,out.extra='',fig.pos='H', eval = FALSE, message=FALSE)

knitr::opts_knit$set(root.dir='./')

```

## Load libraries and set up parameters 

```{r loadLibs, message=FALSE, warning=FALSE,eval=TRUE}
#working directory 
setwd("~/Documents/GitHub/pipefish_sbge/stigmatopora/S_macropterygia")

#This is a cohesive list of all the libraries used in this document 
library(spfTools)
library(DESeq2)
library(ggplot2)
library(pheatmap)
library(magick)
library(patchwork)
library(tidyverse)
library(UpSetR)
library(EnvStats)
library(knitr)
library(PCAtools)

```

```{r setParams, eval=TRUE}
sex_bias_colors <- c("FB" = "#7fc97f", "MB" = "#beaed4", "UB" = "darkgray")

biased_bins <- c("Low", "Med", "High", "Extreme", "Sex.specific")
labs<-c("Low", "Med", "High", "Extreme", "Specific")

sex_cols <- c("F" = "#7fc97f", "M" = "#beaed4" )
sex_shapes <- c(
  Gill=16, 
  Liver=17, 
  Ovaries=15,
  Testis=15,
  Gonad=15)

organ_cols<-c("Gill" = "#20B2AA",
              "Gonad" = "#EEB422", 
              "Liver" = "#EE8262")

```

``` {r getSamplesInfo, eval=TRUE}

#The samples file generated for tximport
samples <- read.table("data/SM_samples.txt", header = TRUE)


#Make sure the conditions are in the samples file as a factor
samples$sex <- as.factor(samples$sex)
samples$organ <- as.factor(samples$organ)

```

### PCA Plots Figures

```{r figPCADataPrep, eval=FALSE}

#The abundance matrix generated via salmon and tximport to be used for the DE analysis
txi.macropterygia <- readRDS("data/txi.salmon_SM.RDS")

#Create the DEseq dataset
dds_PCA <- DESeqDataSetFromTximport(txi.macropterygia, 
                                   colData = samples,
                                   design = ~ sex)
##Remove S10, S23, and S30 from the dataset
dds_PCA <- dds_PCA[, !(dds_PCA$ID %in% c("S10", "S23", "S30"))]

#only keeping rows that have at least 10 reads total
keep <- rowSums(counts(dds_PCA)) >= 10
dds_PCA <- dds_PCA[keep, ]


#Generate the expression values
dds_PCA_exp <- DESeq(dds_PCA)

#Transform the data
vsd_PCA <- vst(dds_PCA_exp, blind=FALSE)
vsd_assay<-assay(vsd_PCA)
#write.csv(vsd_assay,"plot_data/vsd_assay.csv", row.names=TRUE)

# get normalised counts
norm_counts<-counts(dds_PCA_exp, normalized = TRUE)
#write.csv(norm_counts, "plot_data/normalized_counts.csv",row.names = TRUE)
```

```{r readCountData}
vsd_assay<-read.csv("plot_data/vsd_assay.csv",
                    row.names = 1)
```

```{r runPCA, eval=FALSE}
p <- pca(assay(vsd_PCA), 
         metadata = colData(dds_PCA))

#Generate the PCA dataframe
pca <- prcomp(t(assay(vsd_PCA)))
pca_plotting_data <- as.data.frame(pca$x)

### SOMETHING WENT WRONG HERE SEND HELP ###

#Add the metadata to the PCA dataset
pca_plotting_data$organ <- samples$organ
pca_plotting_data$sex <- samples$sex

#Calculate the percent variation attributed to each axis 
percents <- round(p$variance, digits = 2)

write.csv(pca$rotation[, 1:4],
          "plot_data/pca_rotation.csv", 
          row.names=TRUE)

write.csv(pca_plotting_data,
          "plot_data/pca_plotting_data.csv", 
          row.names = TRUE)

write.table(percents,
            "plot_data/PCA_percents.txt", 
            row.names = FALSE)

```

```{r getPCAdata}
pca_plotting_data <- read.csv("plot_data/pca_plotting_data.csv",
                              row.names = 1)
percents <- unlist(read.delim("plot_data/PCA_percents.txt"))
pca_rotation <- read.csv("plot_data/pca_rotation.csv",
                         row.names = 1)
```


### Fig. PCA Panels A, B, and C - PCA Plots

```{r figPCAa}

#Calculate the percent variation attributed to each axis 
pcaData <- plotPCA(vsd_PCA, intgroup = c("organ", "sex"), returnData = TRUE, ntop = nrow(dds_PCA))
percentVar <- round(100 * attr(pcaData, "percentVar"))


my_colors <- c("Gill" = "#6E8B3D75", "Gonad" = "#EEB42275", "Liver" = "#EE826275")
my_shapes <- c(16, 17)

pdf("figs/Fig_PCA1.pdf",height = 6,width=6)
par(mfrow=c(1,2))
ggplot(pca_plotting_data, aes(x=PC1, y=PC2, color = organ, shape = sex)) +
  scale_color_manual(values = my_colors) +
  scale_shape_manual(values = my_shapes) +
  geom_point(aes(size = organ)) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC2: ",percentVar[2],"% variance")) + 
  coord_fixed() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(color = "black")) +
  geom_hline(yintercept = 0,
             linetype = 'dashed') +
  geom_vline(xintercept = 0,
             linetype = 'dashed')

dev.off()
```

```{r figPCAb}

#Calculate the percent variation attributed to each axis 
pcaData <- plotPCA(vsd_PCA, intgroup = c("organ", "sex"), returnData = TRUE, ntop = nrow(dds_PCA))
percentVar <- round(100 * attr(pcaData, "percentVar"))


my_colors <- c("Gill" = "#6E8B3D75", "Gonad" = "#EEB42275", "Liver" = "#EE826275")
my_shapes <- c(16, 17)

pdf("figs/Fig_PCA2.pdf",height = 6,width=6)
par(mfrow=c(1,2))
ggplot(pca_plotting_data, aes(x=PC1, y=PC3, color = organ, shape = sex)) +
  scale_color_manual(values = my_colors) +
  scale_shape_manual(values = my_shapes) +
  geom_point(aes(size = organ)) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC3: ",percentVar[3],"% variance")) + 
  coord_fixed() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(color = "black")) +
  geom_hline(yintercept = 0,
             linetype = 'dashed') +
  geom_vline(xintercept = 0,
             linetype = 'dashed')

dev.off()
```

```{r figPCAc}

#Calculate the percent variation attributed to each axis 
pcaData <- plotPCA(vsd_PCA, intgroup = c("organ", "sex"), returnData = TRUE, ntop = nrow(dds_PCA))
percentVar <- round(100 * attr(pcaData, "percentVar"))


my_colors <- c("Gill" = "#6E8B3D75", "Gonad" = "#EEB42275", "Liver" = "#EE826275")
my_shapes <- c(16, 17)

pdf("figs/Fig_PCA3.pdf",height = 6,width=6)
par(mfrow=c(1,2))
ggplot(pca_plotting_data, aes(x=PC1, y=PC4, color = organ, shape = sex)) +
  scale_color_manual(values = my_colors) +
  scale_shape_manual(values = my_shapes) +
  geom_point(aes(size = organ)) +
  xlab(paste0("PC1: ",percentVar[1],"% variance")) +
  ylab(paste0("PC4: ",percentVar[4],"% variance")) + 
  coord_fixed() +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(), 
        panel.background = element_blank(), 
        axis.line = element_line(color = "black")) +
  geom_hline(yintercept = 0,
             linetype = 'dashed') +
  geom_vline(xintercept = 0,
             linetype = 'dashed')

dev.off()
```

### Fig. PCA Panels D, E, F, and G - Heatmaps

```{r heatmapData}

df <- as.data.frame(samples[,c("sex", "organ")])
rownames(df) <- samples$ID
df$organ <- as.character(df$organ)
```

```{r heatmapSetup}
ann_colors = list(
  sex=sex_cols,
  organ=organ_cols
)

col_order<-c(
  rownames(df[df$sex=="F"&df$organ=="Gill",]),
  rownames(df[df$sex=="M"&df$organ=="Gill",]),
  rownames(df[df$sex=="F"&df$organ=="Gonad",]),
  rownames(df[df$sex=="M"&df$organ=="Gonad",]),
  rownames(df[df$sex=="F"&df$organ=="Liver",]),
  rownames(df[df$sex=="M"&df$organ=="Liver",])
)
  
```

```{r savePheatmapFxn}

# from https://stackoverflow.com/questions/43051525/how-to-draw-pheatmap-plot-to-screen-and-also-save-to-file
save_pheatmap_pdf <- function(x, filename, width=7, height=7) {
  stopifnot(!missing(x))
  stopifnot(!missing(filename))
  pdf(filename, width=width, height=height)
  grid::grid.newpage()
  grid::grid.draw(x$gtable)
  dev.off()
}

```

```{r figPCAd}

pc1 <- pheatmap(vsd_assay[which(abs(pca_rotation[,1]) >= 0.02), col_order], 
              cluster_rows = FALSE, 
              show_rownames = FALSE, 
              cluster_cols = FALSE, 
              show_colnames = FALSE,
              annotation_col = df,
              annotation_colors=ann_colors,
              cellwidth = 9,
              fontsize = 16,
              annotation_legend = FALSE,
              main = "Top loading genes on PC1")

save_pheatmap_pdf(pc1, "figs/FigPCA_pc1_heatmap.pdf",width=6,height=6)

```

```{r figPCAe}

pc2 <- pheatmap(vsd_assay[which(abs(pca_rotation[,2]) >= 0.02),col_order], 
              cluster_rows = FALSE, 
              show_rownames = FALSE, 
              cluster_cols = FALSE, 
              show_colnames = FALSE,
              annotation_col = df,
              annotation_colors=ann_colors,
              cellwidth = 9,
              fontsize = 16,
              annotation_legend = FALSE,
              main = "Top loading genes on PC2")

save_pheatmap_pdf(pc2, "figs/FigPCA_pc2_heatmap.pdf",width=6,height=6)

```

```{r figPCAf}
pc3 <- pheatmap(vsd_assay[which(abs(pca_rotation[,3]) >= 0.02),col_order], 
              cluster_rows = FALSE, 
              show_rownames = FALSE, 
              cluster_cols = FALSE, 
              show_colnames = FALSE,
              annotation_col = df,
              annotation_colors=ann_colors,
              cellwidth = 9,
              fontsize = 16,
              annotation_legend = FALSE,
              border_color = NA,
              main = "Top loading genes on PC3")

save_pheatmap_pdf(pc3, "figs/FigPCA_pc3_heatmap.pdf",width=6,height=6)

```

```{r figPCAg}

pc4 <- pheatmap(vsd_assay[which(abs(pca_rotation[,4]) >= 0.02),col_order], 
              cluster_rows = FALSE, 
              show_rownames = FALSE, 
              cluster_cols = FALSE, 
              show_colnames = FALSE,
              annotation_col = df,
              annotation_colors=ann_colors,
              cellwidth = 9,
              fontsize = 16,
              border_color = NA,
              main = "Top loading genes on PC4")

save_pheatmap_pdf(pc4, "figs/FigPCA_pc4_heatmap.pdf",width=7.2,height=6)

```

### Fig. PCA Assembly

```{r assembleFig2, message=FALSE}
figPCAa <- image_ggplot(image_read_pdf('figs/Fig_PCA1.pdf'),
                        interpolate = TRUE)
figPCAb <- image_ggplot(image_read_pdf('figs/Fig_PCA2.pdf'),
                        interpolate = TRUE)
figPCAc <- image_ggplot(image_read_pdf('figs/Fig_PCA3.pdf'),
                        interpolate = TRUE)
figPCAd <- image_ggplot(image_read_pdf('figs/FigPCA_pc1_heatmap.pdf'),
                        interpolate = TRUE)
figPCAe <- image_ggplot(image_read_pdf('figs/FigPCA_pc2_heatmap.pdf'),
                        interpolate = TRUE)
figPCAf <- image_ggplot(image_read_pdf('figs/FigPCA_pc3_heatmap.pdf'),
                        interpolate = TRUE)
figPCAg <- image_ggplot(image_read_pdf('figs/FigPCA_pc4_heatmap.pdf'),
                        interpolate = TRUE)

figPCA <- wrap_plots(
  figPCAa,
  figPCAb,
  figPCAc,
  figPCAd,
  figPCAe,
  figPCAf,
  figPCAg,
  design="ABC#
  DEFG"
)
figPCA <- figPCA + plot_annotation(tag_levels = 'A')

ggsave("figs/FigPCA.pdf",figPCA, height=4, width=5)
ggsave("figs/FigPCA.png",figPCA, height=4, width=5) # also save as a png
```

## Figure Sex-bias

```{r figSBData}

logFC_long <- read.csv("data/logFC_long_sexbias.csv")
organs <- levels(as.factor(logFC_long$tissue))
ymax <- max(abs(logFC_long$logFC),
            na.rm = TRUE)+5

```

### Fig. Sex-bias boxplots

```{r figSB-boxplots}
pdf("figs/FigSB_logFC_boxplots.pdf", width = 10, height=4)
par(mfrow=c(1,4), 
    oma=c(4,5,2,8), 
    mar=c(1,1,1,0))

for(organ in organs){
  
  # add jittered points
  plot(abs(logFC_long$logFC[logFC_long$tissue==organ]) ~ 
           jitter(as.numeric(as.factor(logFC_long$bias[logFC_long$tissue==organ]))),
         col="#00000075", 
       axes=FALSE,
       cex.main=2,
       xlim=c(0,4),
       ylim=c(0,ymax)
       )
  
  # make the boxplot
  boxplot(
    abs(logFC_long$logFC[logFC_long$tissue==organ]) ~ logFC_long$bias[logFC_long$tissue==organ],
    col=scales::alpha(sex_bias_colors,0.75),
    add = TRUE,
    yaxt='n',
    las=1,
    cex.axis=1.75,
    frame=FALSE,
    lwd=1.5,
    outline=FALSE# do not plot outliers
  )
  # make the axis lines longer and thicker
  axis(1, labels=NA,at=-1:4,lwd=2, lwd.ticks=0, las = 3, cex.axis = 1.5)
  axis(2,labels=seq(-5,ymax,10),
       line=NA, at=seq(-5,ymax,10), 
       lwd=2,ylim=c(0,ymax),cex.axis=2,las=2)
  
  mtext(organ, cex=1.5,outer=FALSE, line=-1)
  
}

# add x axis label
mtext("Bias level",side = 1,cex=1.5, outer=TRUE, line=2)

# add y axis label
mtext(expression("|log"[2]*"FC|"),side = 2,cex=1.5, outer=TRUE, line=2.25)

# add legend
spfTools::outer_legend("right",
                       legend=c("Female\nbiased",
                                "Male\nbiased",
                                "Unbiased"),
                       pt.bg=sex_bias_colors,
                       pch=22,
                       bty='n',
                       ncol=1,
                       cex=2,
                       y.intersp = 1.5,
                       pt.cex=2)

dev.off()
```

### Fig. SB - categories

```{r figSB-cat}
#Make a vector that contains all of the groupings
biased_bins <- c("Unbiased", "Low", "Med", "High", "Extreme", "Sex-specific")

#Create a new column in the dataset and use ifelse statements to set the category limits
#abs(logFC) was used to account for the fem-biased genes possessing negative values
logFC_long$bias_cat <- ifelse(logFC_long$bias == "UB",
                              biased_bins[1],
                              ifelse(abs(logFC_long$logFC) >= 2 & abs(logFC_long$logFC) < 3,
                                     biased_bins[2],
                                     ifelse(abs(logFC_long$logFC) >= 3 & abs(logFC_long$logFC) < 5,
                                            biased_bins[3],
                                            ifelse(abs(logFC_long$logFC) >= 5 & abs(logFC_long$logFC) < 10,
                                                   biased_bins[4],
                                                   biased_bins[5])
                                            )
                                     )
                              )

#Making sure the genes we categorized as sex-specific are labeled as sex-specific for their bias cat. in the dataset
organs <- c("Gill", "Gill", "Gonad", "Gonad", "Liver", "Liver")
bias <- c("MB", "FB", "MB", "FB", "MB", "FB")

for(i in 1:length(SN_sex_specific_genes)){

  tmp <- SN_sex_specific_genes[[i]]
  tmp <- as.data.frame(tmp)
  tmp$geneID <- rownames(tmp)
  
  for(j in 1:nrow(tmp)){
    
    one_gene <- tmp[j, ]
    
    if(one_gene[["geneID"]] %in%
       logFC_long[logFC_long$tissue == organs[[i]] &
                  logFC_long$bias == bias[[i]],"geneID"]){
       
      logFC_long[logFC_long$geneID == one_gene[["geneID"]] &
                   logFC_long$tissue == organs[[i]] &
                   logFC_long$bias == bias[[i]],
                 "bias_cat"] <- "Sex-specific"
    }else{
      
      one_gene_dat <- data.frame(matrix(ncol= ncol(logFC_long),
                                        nrow=1))
      colnames(one_gene_dat) <- colnames(logFC_long)
      
      one_gene_dat$tissue <- organs[[i]]
      one_gene_dat$geneID <- one_gene[["geneID"]]
      one_gene_dat$bias <- bias[[i]]
      one_gene_dat$bias_cat <- "Sex-specific"
      rownames(one_gene_dat) <- NULL
      
      logFC_long <- rbind(one_gene_dat, logFC_long)
      
      rownames(logFC_long) <- NULL
    }
  }
 }

#Create  subset of our long dataset that does not include the non-biased genes
logFC_long_noNB <- logFC_long[logFC_long$bias_cat != "Unbiased",]

#Make a table to count the number of genes in each category for each organ
bias_cat_table <- table(logFC_long_noNB$bias, logFC_long_noNB$bias_cat, logFC_long_noNB$tissue)

#Add the counts of sex-specific genes to the table
bias_cat_gill <- bias_cat_table[,, "Gill"]

bias_cat_gonad <- bias_cat_table[,, "Gonad"]

bias_cat_liver <- bias_cat_table[,, "Liver"]

#Make and save the figs
pdf("figs/FigSB_biasCat_counts_alt.pdf",width = 10, height=4)
ymax <- max(c(unlist(bias_cat_gill),
            unlist(bias_cat_gonad),
            unlist(bias_cat_liver)))+500

par(mfrow=c(1, 3), oma=c(6,4,2,8), mar=c(1,2.5,2,0), 
    cex.main=2,
    cex.axis=2)

#Plot the counts for each tissue type
barplot(bias_cat_gill[,biased_bins[biased_bins!="Unbiased"]], 
        beside = TRUE, 
        ylim = c(0, max(bias_cat_gill) + 1), 
        col = c("#7fc97f", "#beaed4"),
        main = "Gill", ylab = "Number of Genes", 
        xlab = "Bias Category")
barplot(bias_cat_gonad[,biased_bins[biased_bins!="Unbiased"]], 
        beside = TRUE, 
        ylim = c(0, max(bias_cat_table) + 1), 
        col = c("#7fc97f", "#beaed4"),
        main = "Gonad")
barplot(bias_cat_liver[,biased_bins[biased_bins!="Unbiased"]], 
        beside = TRUE, 
        ylim = c(0, max(bias_cat_liver) + 1), 
        col = c("#7fc97f", "#beaed4"),
        main = "Liver")
#legend("topright", legend = c("Female-biased", "Male-biased"), fill = c("#7fc97f", "#beaed4"))

mtext("Number of Genes",2,outer=TRUE, cex=1.5, line=2.25)
mtext("Bias category",1, outer=TRUE, cex=1.5, line=4)

outer_legend("right", 
       legend = c("Female\nbiased", "Male\nbiased"), 
       pt.bg = sex_cols,
       pch=22,
       bty='n',
       ncol=1,
       cex=2,
       y.intersp = 1.5,
       pt.cex=2)
dev.off()

```

### Fig. SB - Upset Plot

```{r figUpsetPlotData}

gonad_mal_biased <- read.table("data/gonad_mal_biased.txt")
gonad_fem_biased <- read.table("data/gonad_fem_biased.txt")

liver_mal_biased <- read.table("data/liver_mal_biased.txt")
liver_fem_biased <- read.table("data/liver_fem_biased.txt")

gill_mal_biased <- read.table("data/gill_mal_biased.txt")
gill_fem_biased <- read.table("data/gill_fem_biased.txt")


listInputall <- list("MB Gonad" = rownames(gonad_mal_biased),
                     "MB Liver" = rownames(liver_mal_biased),
                     "MB Gill" = rownames(gill_mal_biased),
                     "FB Gonad" = rownames(gonad_fem_biased),
                     "FB Liver" = rownames(liver_fem_biased),
                     "FB Gill" = rownames(gill_fem_biased))

```

```{r figUpsetPlot, eval=FALSE}

#Colours will be added manually in Adobe Illustrator 
pdf("figs/FigSB_sexbias_upset.pdf",width = 10, height=7)
upset(fromList(listInputall),
      mainbar.y.label = "# Shared Sex-Biased Genes",
      sets.x.label = "# Sex-Biased Genes",
      point.size = 3,
      nsets = 8,
      nintersects = NA,
      text.scale = c(2, 2, 2, 1.5, 2, 1.5)
)
dev.off()

```

### Fig. SB Assembly

```{r fig3, message=FALSE}

figSBa <- image_ggplot(image_read_pdf('figs/FigSB_logFC_boxplots.pdf'),interpolate = TRUE)
figSBb <- image_ggplot(image_read_pdf('figs/FigSB_biasCat_counts.pdf'),interpolate = TRUE)
figSBc <- image_ggplot(image_read_pdf('figs/FigSB_sexbias_upset_color.pdf'),interpolate = TRUE)


figSB <- wrap_plots(
  figSBa,
  figSBb,
  figSBc,
  nrow = 3
  #design=design
)

figSB <- figSB + plot_annotation(tag_levels = 'A')
figSB

ggsave("figs/FigSB.pdf",figSB, height=10, width=6)
ggsave("figs/Fig3.png",fig3, height=6, width=8)

```





