---
title: "Figure creation for paper describing sex-biased gene expression in _Stigmatopora macropterygia_"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    number_sections: yes
    toc: true
header-includes: >
  \usepackage{lipsum}
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir='../',fig_path="../imgs/")
knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```
```{r setdir}
knitr::opts_knit$set(root.dir='../',
                     fig_path="../figs/")
```
```{r}
library(magick)
library(patchwork)
library(ggplot2)
library(vioplot)
```


```{r loadData}
vsd<-readRDS("data/vsd.RDS")
logFC_long <- read.csv("data/logFC_long_sexbias.csv")
```
```{r setParams}
#Setting the shapes I want to show up for the different organs
organ_shapes <- c(Gill = 16, Liver = 17, Gonad = 15)

#Setting the colors I want for each sex
sex_cols <- c("F" = "#7fc97f", "M" = "#beaed4")

bias_colors <- c("FB" = "#7fc97f", "MB" = "#beaed4", "UB" = "#A9A9A975") 
organ_cols<-c("Gill" = "#20B2AA",
              "Gonad" = "#EEB422", 
              "Liver" = "#EE8262")
```

## Figure 1: General patterns


#### Making the combined figure


```{r assembleFigPCA, message=FALSE}
figPCAa <- image_ggplot(image_read_pdf('figs/Fig_PCA1v2.pdf'),
                        interpolate = TRUE)
figPCAb <- image_ggplot(image_read_pdf('figs/Fig_PCA1v3.pdf'),
                        interpolate = TRUE)
wgcnaOrgan<-image_ggplot(image_read_pdf('figs/moduleOrganHeatmap.pdf'),
                        interpolate = TRUE)
wgcnaSex<-image_ggplot(image_read_pdf('figs/moduleSexHeatmap.pdf'),
                        interpolate = TRUE)

# make two patchworks
pcas <- figPCAa + figPCAb
wgcnas <- wgcnaOrgan + wgcnaSex

# put the patchworks together
figPCA <-  wrap_plots(pcas,
                      wgcnas,
                      ncol = 1 
                      ) + 
  plot_annotation(tag_levels = 'A') 

ggsave("figs/Fig1.pdf", figPCA, height=4, width=5)
ggsave("figs/Fig1.png", figPCA, height=4, width=5) # also save as a png
```


```{r showAssembledFigPCA, eval=TRUE}
figPCA
```

```{r assembleFigPCA-heatmaps}

figPCAc <- image_ggplot(image_read_pdf('figs/Fig_pc1_heatmap.pdf'),
                        interpolate = TRUE)
figPCAd <- image_ggplot(image_read_pdf('figs/Fig_pc2_heatmap.pdf'),
                        interpolate = TRUE)
figPCAe <- image_ggplot(image_read_pdf('figs/Fig_pc3_heatmap.pdf'),
                        interpolate = TRUE)

hms <- figPCAc + figPCAd + figPCAe

# put the patchworks together
figPCA_supp_hm <-  wrap_plots(hms, nrow=1) + 
  plot_annotation(tag_levels = 'A') 

ggsave("figs/FigPCA_heatmaps_supp.pdf", figPCA_supp_hm, height=3.5, width=6)
ggsave("figs/FigPCA_heatmaps_supp.png", figPCA_supp_hm, height=3.5, width=6)
```

```{r assembleFigPCA-supp, message=FALSE}
figPCA4 <- image_ggplot(image_read_pdf('figs/Fig_PCA1v4.pdf'),
                        interpolate = TRUE)
figPCA4_hm <- image_ggplot(image_read_pdf('figs/Fig_pc4_heatmap.pdf'),
                           interpolate = TRUE)

# put the patchworks together
figPCA_supp <-  wrap_plots(figPCA4, figPCA4_hm, ncol=2) + 
  plot_annotation(tag_levels = 'A') 

ggsave("figs/FigPCA_supp.pdf", figPCA_supp, height=4, width=8)
ggsave("figs/FigPCA_supp.png", figPCA_supp, height=4, width=8) # also save as a png
```




## Figure 2: Sex differences in overall expression

Show: 

- violin plots of expression
- upset plot

```{r}
fc_var_aov <- aov(rank(abs(logFC_long$logFC)) ~ logFC_long$bias*logFC_long$tissue)
labs<-multcompLetters4(fc_var_aov, TukeyHSD(fc_var_aov))
labs<-labs$`logFC_long$bias:logFC_long$tissue`
labs<-labs$Letters[c("FB:Gill","MB:Gill","UB:Gill",
                     "FB:Gonad","MB:Gonad","UB:Gonad",
                     "FB:Liver","MB:Liver","UB:Liver")]
```

```{r}
pdf("figs/logFC_violin.pdf",width = 10, height=4)
par(mar=c(3,4,1,1))
plot(0:9,
     seq(0,50,length.out=10),
     type='n',
     axes=FALSE,
     xlab="",
     ylab="|logFC|"
      )
abline(h=2,lwd=2,lty=2)
vioplot(abs(logFC)~bias+tissue,
        data=logFC_long,
        plotCentre = "line", side = "left",
        col=rep(bias_colors,3),
        axes=FALSE,
        xaxt='n',
        add=TRUE,
        las=1,
        ylim=c(0,50))
axis(1, pos=0, at=c(2,5,8),
     labels=c("Gill","Gonad","Liver"),tick = FALSE)
axis(2, las=1)

cnts<-table(logFC_long$bias,logFC_long$tissue)
text(x=1:9,
     y=rep(15,9),
     labels=paste0("n=",cnts),
     col=rep(bias_colors,3),
     srt=270,
     pos = 4)


legend("top",
       legend = c("Female-biased", "Male-biased","Unbiased"), 
       fill = bias_colors,
       bty='n',
       ncol = 3)

text(x=1:9,
     y=rep(-1,9),
     labels = labs,
     xpd=TRUE)
dev.off()
```

```{r, message=FALSE}
vio1<-image_ggplot(image_read_pdf('figs/logFC_violin.pdf'),
                        interpolate = TRUE)
vio2 <- image_ggplot(image_read_pdf('figs/WGCNA_logFC.pdf'),
                           interpolate = TRUE)
upset <- image_ggplot(image_read_pdf('figs/upset.pdf')[2],
                          interpolate = TRUE)
# put the patchworks together
fig2 <-  wrap_plots(vio1,
                           upset,
                           vio2,
                    nrow=3
  
) + 
  plot_annotation(tag_levels = 'A') 

ggsave("figs/Fig2.pdf", fig2, height=8, width=6)
ggsave("figs/Fig2.png", fig2, height=8, width=6) # also save as a png
```
```{r}
fig2
```


## Figure 3: Pleiotropy as measured by tissue specificity


```{r}
logFC_long<-read.csv("data/logFC_long_taubiasSB.csv")
logFC_long_all<- read.csv("data/logFC_long_taubias_SS.csv", 
                          stringsAsFactors = TRUE)
logFC_long_all$bias_cat<-factor(logFC_long_all$bias_cat,
                                levels=c("Unbiased","Low","Med","High","Extreme","Sex-specific"))

# create plotting categories
logFC_long_all$group<-paste0(logFC_long_all$bias_cat,
                             logFC_long_all$bias)
logFC_long_all$group<-factor(logFC_long_all$group,
                             levels=c(
                               "UnbiasedUB",
                               "LowFB",
                               "MedFB",
                               "HighFB",
                               "ExtremeFB",
                               "Sex-specificFB",
                               "LowMB",
                               "MedMB",
                               "HighMB",
                               "ExtremeMB",
                               "Sex-specificMB"
                             ))
```

### correlation plots

```{r}
par(mar=c(3,5.5,1,1))

for(organ in c("Gill","Liver","Gonad")){
  cairo_pdf(paste0("figs/",organ,"_logFC_tau.pdf"),height=5,width=7)
  logFC_long$abs_logFC<-abs(logFC_long$logFC)
  plot(logFC_long[logFC_long$tissue==organ & logFC_long$bias=="MB",]$tau~logFC_long[logFC_long$tissue==organ & logFC_long$bias=="MB",]$abs_logFC,
       bty='l',
       col=scales::alpha(sex_cols["M"],0.5),
       pch=17,
       xlab="|logFC|",
       ylab=expression(tau["TPM"]),
       main=organ,
       cex.axis=1.15,
       cex.lab=1.15
       )
  points(logFC_long[logFC_long$tissue==organ & logFC_long$bias=="FB",]$tau~logFC_long[logFC_long$tissue==organ & logFC_long$bias=="FB",]$abs_logFC,
       bty='l',
       col=scales::alpha(sex_cols["F"],0.5),
       pch=16)
  abline(lm(logFC_long[logFC_long$tissue==organ & logFC_long$bias=="MB",]$tau~logFC_long[logFC_long$tissue==organ & logFC_long$bias=="MB",]$abs_logFC),
         lwd=2,
         col=sex_cols["M"])
  abline(lm(logFC_long[logFC_long$tissue==organ & logFC_long$bias=="FB",]$tau~logFC_long[logFC_long$tissue==organ & logFC_long$bias=="FB",]$abs_logFC),
         lwd=2,
         col=sex_cols["F"])
  dev.off()
}



```



### by bias category

```{r}
for(organ in c("Gill","Liver","Gonad")){
  cairo_pdf(paste0("figs/Tau_",organ,".pdf"),height=5,width=7)
  par(mar=c(3,5.5,1,1))
  r<-ridgeline(x=logFC_long_all$tau[logFC_long_all$tissue==organ],
            y=logFC_long_all$group[logFC_long_all$tissue==organ],
            #palette = scales::alpha(c(bias_colors["UB"],rep(sex_cols,5)),0.75),
            #border = scales::alpha(c(bias_colors["UB"],rep(sex_cols,5)),0.75),
            # labels=c("Unbiased",
            #          "Low","",
            #          "Med","",
            #          "High","",
            #          "Extreme","",
            #          "Sex-specific",""),
            palette = scales::alpha(c(bias_colors["UB"],
                                      rep(sex_cols["F"],5),
                                      rep(sex_cols["M"],5)),0.75),
            border = scales::alpha(c(bias_colors["UB"],
                                      rep(sex_cols["F"],5),
                                      rep(sex_cols["M"],5)),0.75),
            labels=c("Unbiased",
                     rep(c("Low",
                     "Med",
                     "High",
                     "Extreme",
                     "Sex-specific"),2)),
            bty='l',
            mode=TRUE)
  mtext(side=3,organ,font=2,cex=1.15)
  mtext(side=1,expression(tau["TPM"]),line=2,cex=1.15)
  dev.off()
}

```

```{r}
corrsGill<-image_ggplot(image_read_pdf('figs/Gill_logFC_tau.pdf'),
                        interpolate = TRUE)
corrsGonad<-image_ggplot(image_read_pdf('figs/Gonad_logFC_tau.pdf'),
                        interpolate = TRUE)
corrsLiver<-image_ggplot(image_read_pdf('figs/Liver_logFC_tau.pdf'),
                        interpolate = TRUE)
tauGill <- image_ggplot(image_read_pdf('figs/Tau_Gill.pdf'),
                        interpolate = TRUE)
tauGonad <- image_ggplot(image_read_pdf('figs/Tau_Gonad.pdf'),
                        interpolate = TRUE)
tauLiver<-image_ggplot(image_read_pdf('figs/Tau_Liver.pdf'),
                        interpolate = TRUE)

# make two patchworks
joys <- tauGill + tauLiver + tauGonad
cors<-corrsGill + corrsLiver + corrsGonad

# put the patchworks together
fig3 <-  wrap_plots(cors,joys,
                      nrow=2
                      ) + 
  plot_annotation(tag_levels = 'A') 
fig3
```


```{r}
ggsave("figs/Fig3.pdf", fig3, height=3, width=6)
ggsave("figs/Fig3.png", fig3, height=3, width=6) # also save as a png
```

