---
title: "Tissue Specificity in _Stigmatopora nigra_"
author: "Emily Beasley"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    fig_caption: yes
    keep_tex: yes
    number_sections: no
    toc: false
header-includes: >
  \usepackage{lipsum}
  \usepackage{float}
  \floatplacement{figure}{H}
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir='../',
                     fig_path="figs/")
```

``` {r library, message = FALSE, warning = FALSE}
setwd("~/Documents/GitHub/pipefish_sbge/stigmatopora/S_nigra")

#This is a cohesive list of all the libraries used in this document

library(DESeq2)
library(spfTools)
library(ggplot2)


```

``` {r read-data, message = FALSE, warning = FALSE}
#The abundance matrix generated via salmon and tximport to be used for the DE analysis
txi.argus <- readRDS("data/txi.salmon_SA.RDS")

#The samples file generated for tximport
samples <- read.table("data/SA_samples.txt", header = TRUE)

samples$group <- factor(paste0(samples$sex, samples$organ))

#Changing "Gonad" to be more descriptive --> testes or ovaries
samples$organ <- ifelse(samples$sex == "F" & samples$organ == "Gonad",
                        paste0("Ovaries"),
                        ifelse(samples$sex == "M" & samples$organ == "Gonad",
                            paste0("Testes"),
                            paste0(samples$organ))
                  )

#Make sure the conditions are in the samples file as a factor
samples$sex <- as.factor(samples$sex)
samples$organ <- as.factor(samples$organ)

#Format colData to be used in the tau function
colData <- as.data.frame(samples)
rownames(colData) <- samples$ID
```